@startuml

:Користувач: as U
(Обрати алгоритм\nкластеризації) as (обрати)


(Відкрити хмару точок) <-- U

(обрати) <-- U
(Обрати алгоритм \n CLOPE) --|> (обрати) 
(Обрати алгоритм \n MST) --|> (обрати)

U -> (Кластеризувати \n хмару точок)
U --> (Відобразити \n хмару точок)
U --> (Відобразити \n  кластеризовану хмару точок)
U --> (Відобразити \n відокремленого кластеру)
(Відобразити статистичний графік) <- U

@enduml
