@startuml

start

:Очистити маркери точок;

while (Є неопрацьовані точки?) is (Так)
:Взяти точку хмари;
while (Для кожного існуючого кластеру?) 
:Вирахувати збільшення;

if (Збільшення менше знайдених раніше?) then (Так)
  :Встановити кластер як найоптимальніший;
endif
endwhile

if (Збільшення оптимального кластеру більше ніж максимально встановлене?) then (Так)
  :Створити новий кластер;
  :Встановити новий кластер як оптимальний;
endif

:Додати точку до оптимального кластеру;

endwhile (Ні)


stop

@enduml