@startuml

start

while (Очікування сигналу?) is (Отримано)

if (Сигнал від Моделі) then (Так)
	:Конвертувати данні для подання на інтерфейс;
	:Педедати ковертовані данні на відображення;
else if (Сигнал від Інтерфейсу) then (Так)
	:Конвертувати данні для подання до моделі;
	:Педедати ковертовані данні на збереження до моделі;
endif

endwhile (додаток вимкнено)


end

@enduml