@startuml

start

:Очистити маркери точок;


partition "Побудування графу"{
:Зформувати kd дерево;

while (Для кожної точки в хмарі?)

	if (Точка опрацьована?) then (Так) 
	else
	:Помітити точку як опрацьовану;
	:Знайти 10 сусідів;
		while (Для кожного знайденого сусіда?)
			if (ребро з сусідом існує?) then (Так)
				:Видалити точку з списку сусідніх;
				:Знайти додаткову сусідню точку;
			else
				:Додати ребро до графу;
				:Для сусідньої точки знайти 10 сусідів;
				-[#green,dashed]-> Рекурсивний виклик;
			endif
		endwhile
	endif

endwhile
}
:Кластеризація;
detach




@enduml