
@startuml

:Побудування графу;
partition "Кластеризація"{

while (Кількість кластерів менше заданої?)
	:Видалити найдовше ребро;
	:Очистити маркери, n=0;

	while (Для кожної точки в хмарі?)
		:Помітити з номером кластеру(n);
		while (Для кожного ребра точки?)
			:Знайти сусідню;

			if (Сусідня опрацьована?) then (Так)
			else
				:Помітити з номером кластеру(n);
				:Знайти ребра сусідньої точки;
				-[#green,dashed]-> Рекурсивний виклик;
			endif
		endwhile
		:n+=1;
	endwhile

endwhile

}
stop

@enduml